# Generated by Django 5.0.4 on 2024-05-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_customuser_employee_id_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(max_length=4000, null=True, verbose_name='private_key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_key',
            field=models.BinaryField(max_length=1000, null=True, verbose_name='public_key'),
        ),
    ]
