# Generated by Django 5.0.4 on 2024-05-12 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrub_hub_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_message_date',
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['date'], name='scrub_hub_c_date_3d7654_idx'),
        ),
    ]
