# Generated by Django 5.0.4 on 2024-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='coverage_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
