# Generated by Django 5.0.4 on 2024-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_notes', '0002_patient_age_patient_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='coverage_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
