# Generated by Django 5.0.4 on 2024-04-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_notes', '0002_patient_coverage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
